### ISSUE TITLE
Open source sdk

### ISSUE THREAD

**Issue by AlvaroVasconcelos** [ConnectyCube/connectycube-flutter-sdk-releases#1]
Hello, congratulations on the idea, it will be a bigger success if the sdk has an open source.

**Comment by TatankaConCube** [comment]
hello @AlvaroVasconcelos, so far, we have not planned to do this. Please tell us, why you need it? Please describe your issue and we will consider it and try to help you.

**Comment by DDavidPrime** [comment]
What I think @AlvaroVasconcelos is trying to say is that almost all Flutter packages are by nature open source. This helps development time as well as gaining a bigger understanding how the sdk functions. This could open up possibilities of further improvement of the sdk. 
Besides the provided documentation, there aren't many sources which can point to specific information/issues regarding the usage of the sdk. Rather than having a separate ticket for the smallest issue, we could all have access to the source and try to figure things out, with minimum dependencies in regard to others.

**Comment by TatankaConCube** [comment]
we support a similar set of features for a lot of platforms and all our SDKs should be compatible with each other, so we can't make this lib open source
